### ISSUE TITLE
Create wiki from TrekTours project initialization task

### ISSUE THREAD

**Issue by WebDevJL** [Puzzlout/DevGuidelines#1]
Take the explanations detailed in https://github.com/Puzzlout/TrekToursFlyer/issues/1 and build a wiki about using Symphony. 

Check your spelling and grammar too ;)

Thanks

**Comment by damirius** [comment]
@WebDevJL 

Since you opened issue on this repo, do you want me to create this wiki here, or on trektoursflyer repo?

**Comment by WebDevJL** [comment]
@damirius yes do it this repository. This is a general repository. This issue will help us work on the future repositories using Symphony. And every guideline in this repository applies to projects in Puzzlout organization. 

Thank you for asking.

**Comment by WebDevJL** [comment]
@damirius can you add a wiki for the translation bundle as well? Thanks.

**Comment by damirius** [comment]
@WebDevJL 

Done, you can read about it and we can talk a little bit (maybe open up different issue) about Lexik Translation bundle which will help us a lot with managing translations and using DB with them.

**Comment by WebDevJL** [comment]
@damirius. Open up the issue on this repo to discuss the matter and explain
briefly how you use it. Then we'll work on implementation on trek tours
flyer.

## 

Jérémie Litzler

## 

Jérémie Litzler
