### ISSUE TITLE
Translations and Lexik Translation bundle

### ISSUE THREAD

**Issue by damirius** [Puzzlout/DevGuidelines#2]
Configuration guidelines and discussion about translation integration in general.

@WebDevJL 

I'll see that I see what's our best way to approach this issue and I'll get back with some ideas and explanations later .

**Comment by WebDevJL** [comment]
@damirius Let's start by describing how you have experienced it in the past and by giving a brief overview of the usage, even if it is just the link to the bundle on Symphony website.

**Comment by damirius** [comment]
@WebDevJL 

It's just more or less wrapper around existing translation component.
Only thing needed is to create domain translation files for the default language and to import it to the DB. So essentially we have to setup some config files, create tables in our db (just run one command line), create our domain translation file and import them by running import command line, that's it.
Usage is the same as for default translator which is explained on wiki. I'll get on to configuring this on my branch (feature_translations) and see if I can push it so you can see how does it looks like. Also want to check if there are any issues about setting it up before we decide 100% if we want to use it.

**Comment by WebDevJL** [comment]
@damirius Wait for me! I will review the info about that and think it through then we will have you do it.

**Comment by damirius** [comment]
@WebDevJL 

No worries, I'm will not start working with anything specific before you give me a green light.
Just testing it out locally currently, to see if everything works fine with translations.

**Comment by damirius** [comment]
@WebDevJL 

Here is the video of translation bundle in action together with built in GUI for lexik bundle
https://drive.google.com/file/d/0B7Laiv0PjSvDa0I3Zy1tZHNXbU0/view

If you wish I can push the branch to github and give you explanation about what's needed for installation.

**Comment by WebDevJL** [comment]
@damirius ok.

**Comment by damirius** [comment]
@WebDevJL 

You can see the new issue on trektoursflyer repo since we are pushing files there https://github.com/Puzzlout/TrekToursFlyer/issues/20

**Comment by WebDevJL** [comment]
@damirius Yes, I will review it tomorrow morning. Thanks.

## 

Jeremie Litzler
